// Generates docs that must stay identical to code: data dictionary, metric dictionary, validation rules, access matrix.
import { writeFileSync } from 'node:fs';
import { DATASET_SPECS } from '../packages/schemas/src/datasets.ts';
import { RULES } from '../packages/schemas/src/rules.ts';
import { METRIC_DEFINITIONS } from '../packages/metrics/src/definitions.ts';
import { PERMISSIONS, ROLES } from '../packages/auth/src/matrix.ts';

const esc = (s: unknown) => String(s ?? '').replace(/\|/g, '\\|');
const table = (head: string[], rows: unknown[][]) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`)].join('\n');
const out = (f: string, body: string) => writeFileSync(new URL(`../docs/${f}`, import.meta.url), body + '\n');
const HDR = '> GENERATED by `scripts/generate-docs.ts` from code. Do not edit by hand. All status values are DRAFT / PENDING HR SIGN-OFF.\n';

out('data-dictionary.md', `# Data Dictionary (Phase 1 datasets)\n\n${HDR}\nOnly Staff, Attendance and Overtime are implemented in Phase 1; other datasets are described in data-inventory.md.\nDates: YYYY-MM-DD. Period: YYYY-MM. Numbers: plain decimals (no thousand separators). CSV UTF-8.\n\n` +
  Object.values(DATASET_SPECS).map((s) => `## ${s.id} (schema ${s.schemaVersion})\n\nGrain: ${s.grain}. Key: \`${s.key.join(', ')}\`\n\n` +
    table(['Field', 'Type', 'Required', 'Allowed values / validation', 'Sensitive', 'Description'], s.fields.map((f) => [f.name, f.type, f.required ? 'Yes' : 'No', [f.allowed ? f.allowed.join(', ') : '', f.min !== undefined ? `>= ${f.min}` : ''].filter(Boolean).join('; ') || '-', f.sensitive ? 'Yes (never in issues/logs)' : 'No', f.description])) ).join('\n\n') +
  `\n\n## org_units (reference, effective-dated)\n\n` + table(['Field', 'Type', 'Required', 'Validation', 'Description'], [
    ['unit_id', 'string', 'Yes', 'Unique', 'Stable id'], ['level', 'enum', 'Yes', 'BANK, DIVISION, DEPARTMENT, UNIT', 'Hierarchy level'], ['name', 'string', 'Yes', 'Matched case-insensitively', 'Display name used in source files'],
    ['parent_id', 'string', 'Yes (except BANK)', 'Parent exactly one level above', 'Parent unit'], ['effective_from', 'date', 'Yes', 'Valid date', ''], ['effective_to', 'date', 'No', '>= effective_from', 'Blank = open-ended'] ]));

out('validation-rules.md', `# Validation Rules\n\n${HDR}\nBlocking = batch cannot be approved. Resolution: FIX_AND_REUPLOAD = cannot be overridden; ACKNOWLEDGE = warning, reason required; FORMAL_RESOLUTION = blocking, may be resolved only with reason + approval reference by an authorised role (audited).\nImplemented=No means documented from the Blueprint but not built in Phase 1.\n\n` +
  table(['Code', 'Severity', 'Blueprint check', 'Datasets', 'Resolution', 'Implemented', 'Description'], RULES.map((r) => [r.code, r.severity, r.category, r.datasets.join(', '), r.resolution, r.implemented ? 'Yes' : 'No', r.description])));

out('metric-dictionary.md', `# Metric Dictionary (KPI Catalogue, Blueprint section 26)\n\n${HDR}\nNo metric is APPROVED. Every definition, denominator, exclusion and threshold below is a proposal awaiting HR sign-off; \`Implemented\` shows what has deterministic code + golden tests in Phase 1. Definitions are versioned configuration in \`packages/metrics/src/definitions.ts\`.\n\n` +
  table(['ID', 'Domain', 'Name', 'Definition', 'Numerator', 'Denominator', 'Exclusions', 'Grain', 'Dimensions', 'Thresholds', 'Owner', 'Version', 'Status', 'Implemented'],
    METRIC_DEFINITIONS.map((d) => [d.id, d.domain, d.name, d.definition, d.numerator, d.denominator, d.exclusions, d.grain, d.dimensions.join(', '), d.thresholds, d.owner, d.version, d.status.replace(/_/g, ' '), d.implemented ? 'Yes' : 'No'])));

const cell = (p: (typeof PERMISSIONS)[number], r: string) => (p.roles.includes(r as never) ? (p.dataLevel === 'METADATA' ? 'Yes' : p.dataLevel) : '-');
out('access-matrix.md', `# Access Matrix\n\n${HDR}\nEnforced server-side by \`packages/auth\` (fail-closed). Scope = permitted org unit and all descendants (Bank > Division > Department > Unit). "Scoped" permissions require the target org unit to be inside the user's scope. Cell = data level the role gets (AGGREGATE / EMPLOYEE_LEVEL) or Yes for metadata-only.\n\n` +
  table(['Permission', 'Module', 'Scoped', ...ROLES, 'Notes'], PERMISSIONS.map((p) => [p.permission, p.module, p.scoped ? 'Yes' : 'No', ...ROLES.map((r) => cell(p, r)), p.notes])) +
  `\n\n## Rules\n\n- ER: employee-level ER data is ER_RESTRICTED only (ASSUMPTION A-10, needs ER leadership decision). Aggregate ER indicators are available to HR Analytics Admin, HR Leadership and ER_RESTRICTED only; small-cell suppression is PENDING.\n- Exports: employee-level exports are HR Analytics Admin only. Aggregate exports come from a published snapshot, are scoped, and are audited. Read-only Leadership and ER_RESTRICTED have no export.\n- Division/Department Heads see published aggregates for their own scope only; no employee-level drill-down (ASSUMPTION A-09).\n- System Admin has no business-data permission (proved by test).\n- Dashboards show published data only, never work-in-progress (Phase 2 enforcement point).\n- Identity: Microsoft Entra ID SSO + MFA is the target; Phase 1 uses a mock provider that refuses to run in production.\n`);
console.log('docs generated');
